FROM alpine AS builder

ARG APPD_AGENT_VERSION
ARG APPD_AGENT_SHA256

RUN apk update \
    && apk upgrade \
    && apk add unzip

COPY MachineAgent-${APPD_AGENT_VERSION}.zip /
RUN if [ "x${APPD_AGENT_SHA256}" != "x" ]; then \ 
	echo "${APPD_AGENT_SHA256} *MachineAgent-${APPD_AGENT_VERSION}.zip" >> appd_checksum \
    && sha256sum -c appd_checksum \
    && rm appd_checksum \
    && unzip -oq MachineAgent-${APPD_AGENT_VERSION}.zip -d /tmp; \
    else \
     unzip -oq MachineAgent-${APPD_AGENT_VERSION}.zip -d /tmp; \
    fi

FROM alpine

RUN apk update \
    && apk upgrade \
    && apk add bash \
    bc \
    coreutils \
    bind-tools \
    dumb-init \
    gawk \
    grep \
    iproute2 \
    procps \
    sed \
    sysstat \
    unzip \
    eudev \
    openjdk11-jre \
    && rm -rf /var/cache/apk/*

ARG APPD_AGENT_VERSION

LABEL name="AppDynamics MachineAgent" \
      vendor="AppDynamics" \
      version="${APPD_AGENT_VERSION}" \
      release="1" \
      url="https://www.appdynamics.com" \
      summary="AppDynamics solution for monitoring infrastructure" \
      description="The MachineAgent monitors resource utilization, server load and processes on the host."

COPY --from=builder /tmp /opt/appdynamics

ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["sh", "-c", "java ${MACHINE_AGENT_PROPERTIES} -jar /opt/appdynamics/machineagent.jar"]