FROM alpine AS builder

ARG APPD_AGENT_VERSION
ARG APPD_AGENT_SHA256

RUN apk update \
    && apk upgrade \
    && apk add unzip

COPY MachineAgent-${APPD_AGENT_VERSION}.zip /
RUN if [ "x${APPD_AGENT_SHA256}" != "x" ]; then \ 
	echo "${APPD_AGENT_SHA256} *MachineAgent-${APPD_AGENT_VERSION}.zip" >> appd_checksum \
    && sha256sum -c appd_checksum \
    && rm appd_checksum \
    && unzip -oq MachineAgent-${APPD_AGENT_VERSION}.zip -d /tmp; \
    else \
     unzip -oq MachineAgent-${APPD_AGENT_VERSION}.zip -d /tmp; \
    fi

ADD LICENSE /licenses/

FROM alpine

RUN apk update \
    && apk upgrade \
    && apk add bash \
    bc \
    coreutils \
    bind-tools \
    dumb-init \
    gawk \
    grep \
    iproute2 \
    procps \
    sed \
    sysstat \
    unzip \
    openjdk11-jre \
    && rm -rf /var/cache/apk/*

COPY --from=builder /tmp /opt/appdynamics
COPY --from=builder /licenses /licenses

ENV MACHINE_AGENT_HOME /opt/appdynamics

WORKDIR ${MACHINE_AGENT_HOME}

COPY updateAnalyticsAgent.sh ./updateAnalyticsAgent.sh
RUN chmod +x ./updateAnalyticsAgent.sh

COPY startup.sh ./startup.sh
RUN chmod +x ./startup.sh

EXPOSE 9090

CMD "./startup.sh"