
FROM registry.access.redhat.com/rhel7-minimal

MAINTAINER support@appdynamics.com

LABEL name="AppDynamics MachineAgent" \
      vendor="AppDynamics" \
      version="4.5.18" \
      release="1" \
      url="https://www.appdynamics.com" \
      summary="AppDynamics solution for monitoring infrastructure" \
      description="The MachineAgent monitors resource utilization, server load and process on the host."

ARG APPD_AGENT_VERSION 
ARG APPD_AGENT_SHA256

RUN microdnf --enablerepo=rhel-7-server-rpms install bash procps sysstat sed coreutils  unzip shadow-utils iproute java-1.8.0-openjdk-headless --nodocs
RUN microdnf clean all

ENV MACHINE_AGENT_HOME /opt/appdynamics
WORKDIR ${MACHINE_AGENT_HOME}

COPY MachineAgent-${APPD_AGENT_VERSION}.zip /
RUN if [ "x${APPD_AGENT_SHA256}" != "x" ]; then \ 
	echo "${APPD_AGENT_SHA256} *MachineAgent-${APPD_AGENT_VERSION}.zip" >> appd_checksum \
    && sha256sum -c appd_checksum \
    && rm appd_checksum \
    && unzip -oq /MachineAgent-${APPD_AGENT_VERSION}.zip -d ${MACHINE_AGENT_HOME}; \
    else \
     unzip -oq /MachineAgent-${APPD_AGENT_VERSION}.zip -d ${MACHINE_AGENT_HOME}; \
    fi

ADD LICENSE /licenses/


RUN groupadd appdynamics && \
    useradd appdynamics -g appdynamics 

COPY updateAnalyticsAgent.sh ./updateAnalyticsAgent.sh
RUN chmod +x ./updateAnalyticsAgent.sh

COPY startup.sh ./startup.sh
RUN chmod +x ./startup.sh

RUN chown -R appdynamics:appdynamics ${MACHINE_AGENT_HOME} && chmod 744 ${MACHINE_AGENT_HOME}

RUN chgrp -R 0 ${MACHINE_AGENT_HOME} && chmod -R g+w ${MACHINE_AGENT_HOME}

USER appdynamics

EXPOSE 9090

CMD "./startup.sh"
