FROM registry.access.redhat.com/rhel7-minimal

MAINTAINER AppDynamics

LABEL name="AppDynamics ClusterAgent" \
      vendor="AppDynamics" \
      version="20.6.0" \
      release="1" \
      url="https://www.appdynamics.com" \
      summary="AppDynamics monitoring solution for applications deployed to Kubernetes clusters" \
      description="The ClusterAgent monitors state of Kubernetes resources and derives metrics to provide visibility into common application impacting issues."


# Install required packages
RUN microdnf --enablerepo=rhel-7-server-rpms install unzip shadow-utils  --nodocs && \
 microdnf clean all

# Install AppDynamics Cluster Agent
ENV CLUSTER_AGENT_HOME /opt/appdynamics/cluster-agent/
ADD cluster-agent.zip /tmp/cluster-agent.zip
ADD LICENSE /licenses/

# Create a group and user
RUN groupadd appdynamics && \
    useradd appdynamics -g appdynamics && \
    mkdir -p ${CLUSTER_AGENT_HOME} && \
    unzip -oq /tmp/cluster-agent.zip -d ${CLUSTER_AGENT_HOME} && \
    rm /tmp/cluster-agent.zip && \
    rm -rf /opt/appdynamics/cluster-agent/config/agent-monitoring.yml && \
    rm -rf /opt/appdynamics/cluster-agent/config/instrumentation.yml && \
    mkdir /opt/appdynamics/cluster-agent/config/agent-monitoring && \
    touch /opt/appdynamics/cluster-agent/config/agent-monitoring/agent-monitoring.yml && \
    ln -s /opt/appdynamics/cluster-agent/config/agent-monitoring/agent-monitoring.yml /opt/appdynamics/cluster-agent/config/agent-monitoring.yml && \
    mkdir /opt/appdynamics/cluster-agent/config/instrumentation && \
    touch /opt/appdynamics/cluster-agent/config/instrumentation/instrumentation.yml && \
    ln -s /opt/appdynamics/cluster-agent/config/instrumentation/instrumentation.yml /opt/appdynamics/cluster-agent/config/instrumentation.yml

# Include start script to configure and start Cluster Agent at runtime
ADD start-appdynamics ${CLUSTER_AGENT_HOME}
RUN mkdir -p ${CLUSTER_AGENT_HOME}/logs && chmod 774 ${CLUSTER_AGENT_HOME}/logs && \
    chmod 744 ${CLUSTER_AGENT_HOME}/start-appdynamics && \
    chown -R appdynamics:appdynamics /opt/appdynamics

RUN chgrp -R 0 /opt/appdynamics && chmod -R g+w /opt/appdynamics

USER appdynamics

# Changing directory to CLUSTER_AGENT_HOME
WORKDIR ${CLUSTER_AGENT_HOME}

# Decided to make this an ENTRYPOINT instead of CMD because the cluster agent should be executed once docker run is
# invoked.
ENTRYPOINT ["/bin/sh"]
CMD ["-c", "./start-appdynamics"]